version: '3'

services:
  app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - DB_HOST=db  # Refers to the db service container
      - DB_USER=${DB_USER}  # Uses the DB_USER variable from .env
      - DB_PASSWORD=${DB_PASSWORD}  # Uses the DB_PASSWORD variable from .env
      - DB_NAME=${DB_NAME}  # Uses the DB_NAME variable from .env
      - DB_PORT=${DB_PORT}  # Uses the DB_PORT variable from .env
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}  # Uses the DB_USER variable from .env
      - POSTGRES_PASSWORD=${DB_PASSWORD}  # Uses the DB_PASSWORD variable from .env
      - POSTGRES_DB=${DB_NAME}  # Uses the DB_NAME variable from .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s